- name: Configure EC2 and Deploy Web App
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and NPM
      apt:
        name:
          - nodejs
          - npm
        state: present

    - name: Create app directory
      file:
        path: /var/www/myapp
        state: directory
        owner: ubuntu

    - name: Copy code from Jenkins workspace to AWS server
      copy:
        src: ./
        dest: /var/www/myapp/

    - name: Install Backend dependencies
      command: npm install
      args:
        chdir: /var/www/myapp/Backend/

    - name: Install Frontend dependencies
      command: npm install
      args:
        chdir: /var/www/myapp/Frontend/

    - name: Start Backend server
      shell: nohup node index.js > backend.log 2>&1 &
      args:
        chdir: /var/www/myapp/Backend/

    - name: Start Frontend server
      shell: nohup env HOST=0.0.0.0 npm run dev > frontend.log 2>&1 &
      args:
        chdir: /var/www/myapp/Frontend/
